name: Cem Uran
theme: minimal-mistakes-jekyll
markdown: kramdown
social-network-links:
  twitter: uranc__
  github: uranc
  linkedin: cem-uran-34143510b
share-links-active:
  twitter: true
  github: true
  linkedin: true
